server:
  port: ":8080"

database:
  dsn: "root:123456@tcp(mysql:3306)/allto?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "redis:6379"
  password: ""

jwt:
  secret: "change-me-in-production"

  smtp:
    host: "wzroyvoqpyxddjae"
    port: 587
    username: "2463301806@qq.com"
    password: ""          # 用环境变量 APP_SMTP_PASSWORD
    from: "2463301806@qq.com"